// This script should error out shall `f` be called outside of `a`'s scope (which it is here)

let f
{
  let a
  f: (#ref(a)) => {a: a + 1}
}

f.()
